DROP TABLE IF EXISTS TBL_BOOKS;

CREATE TABLE TBL_BOOKS (
   id INT AUTO_INCREMENT NOT NULL,
   ISBN VARCHAR(250) PRIMARY KEY,
   title VARCHAR(250) NOT NULL,
   author VARCHAR(250),
   publish_year INT
);